services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
    container_name: chat-server
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - PORT=3000
